/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import login_register.supplier_landing;
import login_register.distributor_landing;
import login_register.admin_login;

/**
 *
 * @author varsh
 */
public class welcome_page extends javax.swing.JFrame {

    /**
     * Creates new form welcome_page
     */
    public welcome_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        supplier_button = new javax.swing.JButton();
        admin_button1 = new javax.swing.JButton();
        distributor_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        title.setForeground(new java.awt.Color(0, 204, 204));
        title.setText("PHARMACY SUPPLY CHAIN");
        main_panel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        supplier_button.setBackground(new java.awt.Color(0, 204, 204));
        supplier_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        supplier_button.setForeground(new java.awt.Color(255, 255, 255));
        supplier_button.setText("SUPPLIER");
        supplier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_buttonActionPerformed(evt);
            }
        });
        main_panel.add(supplier_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        admin_button1.setBackground(new java.awt.Color(0, 204, 204));
        admin_button1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        admin_button1.setForeground(new java.awt.Color(255, 255, 255));
        admin_button1.setText("ADMIN");
        admin_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_button1ActionPerformed(evt);
            }
        });
        main_panel.add(admin_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        distributor_button.setBackground(new java.awt.Color(0, 204, 204));
        distributor_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        distributor_button.setForeground(new java.awt.Color(255, 255, 255));
        distributor_button.setText("DISTRIBUTOR");
        distributor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributor_buttonActionPerformed(evt);
            }
        });
        main_panel.add(distributor_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 510, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_buttonActionPerformed
        // TODO add your handling code here:
        supplier_landing s = new supplier_landing();
        dispose();
        s.setVisible(true);
    }//GEN-LAST:event_supplier_buttonActionPerformed

    private void admin_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_button1ActionPerformed
        // TODO add your handling code here:
        admin_login a = new admin_login();
        dispose();
        a.setVisible(true);
    }//GEN-LAST:event_admin_button1ActionPerformed

    private void distributor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributor_buttonActionPerformed
        // TODO add your handling code here:
        distributor_landing s = new distributor_landing();
        dispose();
        s.setVisible(true);
    }//GEN-LAST:event_distributor_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_button1;
    private javax.swing.JButton distributor_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JButton supplier_button;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
