/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distributor;

import login_register.distributor_landing;

/**
 *
 * @author Sweety
 */
public class distributor_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Distributor_Dashboard
     */
    public distributor_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        main_panel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        view_orders = new javax.swing.JButton();
        place_order = new javax.swing.JButton();
        back_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N

        main_panel1.setBackground(new java.awt.Color(255, 255, 255));
        main_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        title.setForeground(new java.awt.Color(0, 204, 204));
        title.setText("DISTRIBUTOR DASHBOARD");
        main_panel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 460, -1));

        view_orders.setBackground(new java.awt.Color(0, 204, 204));
        view_orders.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        view_orders.setForeground(new java.awt.Color(255, 255, 255));
        view_orders.setText("VIEW ORDERS");
        view_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_ordersActionPerformed(evt);
            }
        });
        main_panel1.add(view_orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 250, 50));

        place_order.setBackground(new java.awt.Color(0, 204, 204));
        place_order.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        place_order.setForeground(new java.awt.Color(255, 255, 255));
        place_order.setText("PLACE ORDERS");
        place_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place_orderActionPerformed(evt);
            }
        });
        main_panel1.add(place_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        back_button1.setBackground(new java.awt.Color(0, 204, 204));
        back_button1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        back_button1.setForeground(new java.awt.Color(255, 255, 255));
        back_button1.setText("←");
        back_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button1ActionPerformed(evt);
            }
        });
        main_panel1.add(back_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(main_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void view_ordersActionPerformed(java.awt.event.ActionEvent evt) {                                            
        orders_view vo = new orders_view();
        dispose();
        vo.setVisible(true);
       
    }                                          

    private void place_orderActionPerformed(java.awt.event.ActionEvent evt) {                                            
        place_orders pd = new place_orders();
        dispose();
        pd.setVisible(true);
    }                                          

    private void back_button1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        distributor_landing w = new distributor_landing();
        dispose();
        w.setVisible(true);
    }                                            

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                    
    private javax.swing.JButton back_button;
    private javax.swing.JButton back_button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel main_panel1;
    private javax.swing.JButton place_order;
    private javax.swing.JButton register_button;
    private javax.swing.JButton register_button1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JButton view_orders;
    // End of variables declaration                  
}
