/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package suppliers;

import login_register.supplier_landing;

/**
 *
 * @author varsh
 */
public class supplier_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form SUPPLIER_DASHBOARD
     */
    public supplier_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        update_button = new javax.swing.JButton();
        insert_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        view_shipment = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        title.setForeground(new java.awt.Color(0, 204, 204));
        title.setText("SUPPLIER DASHBOARD");
        main_panel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        update_button.setBackground(new java.awt.Color(0, 204, 204));
        update_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        update_button.setForeground(new java.awt.Color(255, 255, 255));
        update_button.setText("UPDATE SHIPMENT");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        main_panel.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 320, -1));

        insert_button.setBackground(new java.awt.Color(0, 204, 204));
        insert_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        insert_button.setForeground(new java.awt.Color(255, 255, 255));
        insert_button.setText("INSERT SHIPMENT");
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });
        main_panel.add(insert_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        back_button.setBackground(new java.awt.Color(0, 204, 204));
        back_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("←");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        main_panel.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        view_shipment.setBackground(new java.awt.Color(0, 204, 204));
        view_shipment.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        view_shipment.setForeground(new java.awt.Color(255, 255, 255));
        view_shipment.setText("VIEW SHIPMENTS");
        view_shipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_shipmentActionPerformed(evt);
            }
        });
        main_panel.add(view_shipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 290, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(145, Short.MAX_VALUE)
                    .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(110, Short.MAX_VALUE)
                    .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        update_shipment u = new update_shipment();
        dispose();
        u.setVisible(true);
    }                                            

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        shipment s = new shipment();
        dispose();
        s.setVisible(true);

    }                                            

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        supplier_landing back = new supplier_landing();
        dispose();
        back.setVisible(true);
    }                                          

    private void view_shipmentActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        shipments_view s = new shipments_view();
        dispose();
        s.setVisible(true);
    }                                            

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                    
    private javax.swing.JButton back_button;
    private javax.swing.JButton insert_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel title;
    private javax.swing.JButton update_button;
    private javax.swing.JButton view_shipment;
    // End of variables declaration                  
}
