/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;
import admin.salesmen.*;
import admin.warehouses.warehouse_landing;
import login_register.*;
import main.welcome_page;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author varsh
 */
public class admin_landing extends javax.swing.JFrame {

    /**
     * Creates new form welcome_page
     */
    public admin_landing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        admin_button1 = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        medicine_button = new javax.swing.JButton();
        warehouse_button = new javax.swing.JButton();
        manufacturer_button = new javax.swing.JButton();
        sales_button = new javax.swing.JButton();
        employees_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        title.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        title.setForeground(new java.awt.Color(0, 204, 204));
        title.setText("PHARMACY SUPPLY CHAIN");

        admin_button1.setBackground(new java.awt.Color(0, 204, 204));
        admin_button1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        admin_button1.setForeground(new java.awt.Color(255, 255, 255));
        admin_button1.setText("ADMIN");
        admin_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_button1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        title1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 204, 204));
        title1.setText("ADMIN PAGE");

        back_button.setBackground(new java.awt.Color(0, 204, 204));
        back_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("←");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        medicine_button.setBackground(new java.awt.Color(0, 204, 204));
        medicine_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        medicine_button.setForeground(new java.awt.Color(255, 255, 255));
        medicine_button.setText("MEDICINES");
        medicine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_buttonActionPerformed(evt);
            }
        });

        warehouse_button.setBackground(new java.awt.Color(0, 204, 204));
        warehouse_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        warehouse_button.setForeground(new java.awt.Color(255, 255, 255));
        warehouse_button.setText("WAREHOUSES");
        warehouse_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouse_buttonActionPerformed(evt);
            }
        });

        manufacturer_button.setBackground(new java.awt.Color(0, 204, 204));
        manufacturer_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        manufacturer_button.setForeground(new java.awt.Color(255, 255, 255));
        manufacturer_button.setText("MANUFACTURERS");
        manufacturer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturer_buttonActionPerformed(evt);
            }
        });

        sales_button.setBackground(new java.awt.Color(0, 204, 204));
        sales_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        sales_button.setForeground(new java.awt.Color(255, 255, 255));
        sales_button.setText("SALESMEN");
        sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_buttonActionPerformed(evt);
            }
        });

        employees_button.setBackground(new java.awt.Color(0, 204, 204));
        employees_button.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        employees_button.setForeground(new java.awt.Color(255, 255, 255));
        employees_button.setText("EMPLOYEES");
        employees_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employees_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manufacturer_button)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(medicine_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sales_button, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(back_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(title1))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(employees_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(warehouse_button)))
                .addGap(34, 34, 34))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title1)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicine_button)
                    .addComponent(sales_button))
                .addGap(50, 50, 50)
                .addComponent(manufacturer_button)
                .addGap(65, 65, 65)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employees_button)
                    .addComponent(warehouse_button))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 570, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -16, 820, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_button1ActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        welcome_page w = new welcome_page();
        dispose();
        w.setVisible(true);
        
    }//GEN-LAST:event_back_buttonActionPerformed

    private void medicine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_buttonActionPerformed
       medicine m = new medicine();
       dispose();
       m.setVisible(true);
    }//GEN-LAST:event_medicine_buttonActionPerformed

    private void warehouse_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouse_buttonActionPerformed
        // TODO add your handling code here:
        warehouse_landing w = new warehouse_landing();
        dispose();
        w.setVisible(true);
    }//GEN-LAST:event_warehouse_buttonActionPerformed

    private void manufacturer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturer_buttonActionPerformed
        // TODO add your handling code here:
       manufacturer m = new manufacturer();
       dispose();
       m.setVisible(true);
    }//GEN-LAST:event_manufacturer_buttonActionPerformed

    private void sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_buttonActionPerformed
        // TODO add your handling code here:
        salesman_landing s = new salesman_landing();
        dispose();
        s.setVisible(true);
    }//GEN-LAST:event_sales_buttonActionPerformed

    private void employees_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employees_buttonActionPerformed
        // TODO add your handling code here:
       employees e = new employees();
       dispose();
       e.setVisible(true);
    }//GEN-LAST:event_employees_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_button1;
    private javax.swing.JButton back_button;
    private javax.swing.JButton employees_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JButton manufacturer_button;
    private javax.swing.JButton medicine_button;
    private javax.swing.JButton sales_button;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JButton warehouse_button;
    // End of variables declaration//GEN-END:variables
}
